export const yandexConditionRu: Record<string, string> = {
  "clear": "Ясно",
  "partly-cloudy": "Малооблачно",
  "cloudy": "Облачно",
  "overcast": "Пасмурно",
  "light-rain": "Небольшой дождь",
  "rain": "Дождь",
  "moderate-rain": "Умеренный дождь",
  "heavy-rain": "Сильный дождь",
  "continuous-heavy-rain": "Длительный сильный дождь",
  "showers": "Ливень",
  "wet-snow": "Дождь со снегом",
  "light-snow": "Небольшой снег",
  "snow": "Снег",
  "snow-showers": "Снегопад",
  "hail": "Град",
  "thunderstorm": "Гроза",
  "thunderstorm-with-rain": "Гроза с дождём",
  "thunderstorm-with-hail": "Гроза с градом",
};
